steps:
  - name: ":rspec:"
    command: "scripts/ci/parallel_specs.sh"
    artifact_paths:
      - "log/**/*"
      - "tmp/screenshots/*.png"
    env:
      RAILS_ENV: test
      DATABASE_URL: postgresql://forem:forem@db:5432/PracticalDeveloper_test
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: rails
      SE_OPTS: '-timeout 10000 -browserTimeout 10000'
      JAVA_OPTS: '-Xmx1024m'
    plugins:
      - docker-compose#v3.7.0:
          run: rails
          config: docker-compose-test.yml
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE
    branches: "mstruve/*"
